### ISSUE TITLE
BGworker cannot reload GUCs

### ISSUE THREAD

**Issue by HUUTFJ** [k-zshiba/pg_count_roles#11]
IIUC, nevertheless GUCs have PGC_SIGHUP context, count_roles worker cannot reload the configuration file based on SIGHUP signal.
This means, e.g., the duration between checks won't be changed if user modifies `check_duration` parameter and runs `pg_ctl reload`.

Can you call `ProcessConfigFile(PGC_SIGHUP)` appropriately? Note that if `database` is modified, we may have to restart the background worker. Because BG workers may not able to change the internal connection.

I think pg_prewarn is your friend:
https://github.com/postgres/postgres/blob/01df14763431df1506cbae206945cd165c66d1d3/contrib/pg_prewarm/autoprewarm.c#L216

**Comment by HUUTFJ** [comment]
Or, if it works as expected, the context should be changed to `PGC_POSTMASTER`.
The context prohibits to change parameters without restart.

**Comment by k-zshiba** [comment]
Thank you for reporting the issue.
As you mentioned, `check_duration` (and `database`) parameter does not update after `pg_ctl reload`.

Calling `ProcessConfigFile(PGC_SIGHUP)` fixes this issue.
Thank you!!

**Comment by HUUTFJ** [comment]
Thanks for updating, but not sure it is sufficient.

* GUC parameter `database` can be updated, but the worker still ignores the change. `pg_count_roles_database` is referred only once.
*  I think The worker won't be stop even if it receives `SIGTERM`.

For second bullet, it is because `die()` does not terminate the process immediately. According to the comment atop the function;

```
/*
 * Shutdown signal from postmaster: abort transaction and exit
 * at soonest convenient time
 */
void
die(SIGNAL_ARGS)
```

After setting the flag, the process will exit when `CHECK_FOR_INTERRUPTS()` is called. I.e., it must be added within the loop.

**Comment by k-zshiba** [comment]
Thank you for reporting additional issue.

On my machine, worker stopped by sending `SIGTERM` using `pg_terminate_backend()` or `kill -TERM`.

However, since `CHECK_FOR_INTERRUPTS()` was adopted by several background workers, including worker_spi, it is also adopted by `pg_count_roles`.

**Comment by k-zshiba** [comment]
> GUC parameter database can be updated, but the worker still ignores the change. pg_count_roles_database is referred only once.

Since `BackgroundWorkerInitializeConnection` (or`BackgroundWorkerInitializeConnectionByOid`) can be called in a background worker once, this behavior is correct.

In this extension, the context of pg_count_roles.database should be `PGC_POSTMASTER`.

https://www.postgresql.org/docs/current/bgworker.html#:~:text=Once%20running%2C%20the,to%20switch%20databases.

**Comment by HUUTFJ** [comment]
> In this extension, the context of pg_count_roles.database should be PGC_POSTMASTER.

+1
