### ISSUE TITLE
001_pg_count_roles.pl may be unstable in dev branch

### ISSUE THREAD

**Issue by HUUTFJ** [k-zshiba/pg_count_roles#16]
While reading the testcode, I started to think the test maybe unstable.

First point:
```
# Check the wait event used by the dynamic bgworker.
$result = $node->safe_psql('postgres', q[SELECT state FROM pg_stat_activity WHERE wait_event = 'PgCountRolesMain';]);
is($result, 'idle', 'dynamic bgworker has reported "PgCountRolesMain" as wait event');
```

I think the `is()` would fail if the worker is running at that time. Can we use `poll_query_until()` to wait until the `state` will be `idle`?

Second point:
```
# Check the "query" column of pg_stat_activity
$result = $node->safe_psql('postgres', q[SELECT query FROM pg_stat_activity WHERE wait_event = 'PgCountRolesMain';]);
is($result, 'SELECT count(*) FROM pg_roles;', 'pg_count_roles_main appears in query column of pg_stat_activity');
```

Not sure, but the attribute will be NULL if the worker has not executed query yet. IIUC, we can use `poll_query_until()` as well.

Third point:
```
my $duration = $end - $start;
is($duration ,5,'Test whether the database is accessed at the interval set in pg_count_roles.check_duration');
```

It will fail if the worker spends more time than five seconds. I think we can use `ok()` instead of `is()`.

Fourth point:
```
$result = $node->safe_psql('mydb', q[SELECT datname FROM pg_stat_activity WHERE wait_event = 'PgCountRolesMain';]);
is($result, 'mydb', 'connect to the database specified in pg_count_roles.database');
```

I think it will fail if the worker has not started yet.

**Comment by k-zshiba** [comment]
Thank you for your comment.

I agree with first, second, and fourth point. 

About third point, I would like to validate that the query is executed at the interval set in pg_count_roles.check_duration.
If I understand correctly, `ok()` checks if the command specified in the argument succeeds.
Is it possible to test query duration using `ok()`?
Or you mean that test script such as checking time should not be included to avoid unstable results?

**Comment by HUUTFJ** [comment]
> If I understand correctly, ok() checks if the command specified in the argument succeeds.

I think you are saying `command_ok()`, which runs a shell command:

```
=item $node->command_ok(...)

Runs a shell command like PostgreSQL::Test::Utils::command_ok, but with PGHOST and PGPORT set
so that the command will default to connecting to this PostgreSQL::Test::Cluster.
```

I meant to say that `ok()` in Test::More module [1], more precisely, `cmp_ok()` seems to be used.
It allows to compare with a binary operator. I.e., how about below?

```
cmp_ok($duration, '>=', 5, Test whether the database is accessed at the interval set in pg_count_roles.check_duration)
```

[1]: https://perldoc.perl.org/Test::More#ok

**Comment by k-zshiba** [comment]
> I think you are saying `command_ok()`, which runs a shell command:

I was saying `command_ok()`. I misunderstood.

> I meant to say that `ok()` in Test::More module [1](https://perldoc.perl.org/Test::More#ok), more precisely, `cmp_ok()` seems to be used. It allows to compare with a binary operator. I.e., how about below?
> 
> ```
> cmp_ok($duration, '>=', 5, Test whether the database is accessed at the interval set in pg_count_roles.check_duration)
> ```
I agree with this idea.
Thank you for your big help.
