### ISSUE TITLE
Unnecessary initialization of StringInfo

### ISSUE THREAD

**Issue by HUUTFJ** [k-zshiba/pg_count_roles#7]
Hi, this repository looks interesting. Nice work!

`StringInfo` is initialized within a main loop, but I think It is needed only once.
Also, since the fixed string is appended, `appendStringInfo()` can be outside the loop.

```
        initStringInfo(&buf);

        /* Build the query string */
        appendStringInfo(&buf,"SELECT count(*) FROM pg_roles;");
```

**Comment by k-zshiba** [comment]
Thank you for your comment.
As you said, `initStringInfo()` and `appendStringInfo()` should be outside of the loop.

When they are inside of it, "query" column of pg_stat_activity has wrong info.
I can fix the issue moving them to the outside. Thank you.

**Comment by HUUTFJ** [comment]
I checked your PR and LGTM. Thanks!
